SEO-176838-vue-ej2-page-with-redirect
syncfusion-content/ej2-vue-docs pull request #181
Opened 2023-10-18 13:21 UTC by Edithabich

Hi @MallikaRK ,
Have made changes to the redirect links,
Please review.
Thanks.

Regards,
Edith.

2023-10-18 13:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176838-vue-ej2-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/ej2-vue-docs/75/)<br/>**

2023-11-01 08:49 UTC, Yvone-Atieno requested changes
Commented

2023-11-01 08:49 UTC, Yvone-Atieno commented on ej2-vue/card/getting-started.md
> +You can import themes for the Syncfusion Vue component in various ways, such as using CSS or SASS styles from npm packages, CDN, [CRG](https://ej2.syncfusion.com/javascript/documentation/common/custo
Check CRG link

2023-11-12 19:48 UTC, Edithabich commented on ej2-vue/card/getting-started.md
> +You can import themes for the Syncfusion Vue component in various ways, such as using CSS or SASS styles from npm packages, CDN, [CRG](https://ej2.syncfusion.com/javascript/documentation/common/custo
resolved

2023-11-12 19:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176838-vue-ej2-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/ej2-vue-docs/109/console)**

2023-11-12 19:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176838-vue-ej2-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/ej2-vue-docs/109/)<br/>**

2023-11-16 06:39 UTC, Yvone-Atieno approved these changes
Approved

2024-01-04 14:13 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-01-04 14:13 UTC, merged