SEO-176927-Vue-Page-With-Redirect-Links
syncfusion-content/ej2-vue-docs pull request #217
Opened 2023-11-14 09:23 UTC by Scholar-jaruha

Hi @MallikaRK,
Please find and review the changes made.
Regards,
Scholar.

2023-11-14 09:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176927-Vue-Page-With-Redirect-Links](https://jenkins.syncfusion.com/job/Content/job/ej2-vue-docs/113/console)**

2023-11-14 09:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176927-Vue-Page-With-Redirect-Links](https://jenkins.syncfusion.com/job/Content/job/ej2-vue-docs/113/)<br/>**

2023-11-22 06:54 UTC, Yvone-Atieno requested changes
Commented

2023-11-22 06:54 UTC, Yvone-Atieno commented on ej2-vue/diagram/interaction.md
> +Get the current selected items from the [`nodes`](https://ej2.syncfusion.com/vue/documentation/api/diagram/selectorModel/#nodes-nodemodel%5B%5D) and [`connectors`](https://ej2.syncfusion.com/vue/docu
Revert changes

2023-11-22 06:54 UTC, Yvone-Atieno commented on ej2-vue/diagram/interaction.md
> +* User handles are used to add some frequently used commands around the selector. To create user handles, define and add them to the [`userHandles`](https://ej2.syncfusion.com/vue/documentation/api/d
Revert changes and check in all places

2023-11-22 07:43 UTC, Scholar-jaruha commented on ej2-vue/diagram/interaction.md
> +* User handles are used to add some frequently used commands around the selector. To create user handles, define and add them to the [`userHandles`](https://ej2.syncfusion.com/vue/documentation/api/d
reverted

2023-11-22 07:44 UTC, Scholar-jaruha commented on ej2-vue/diagram/interaction.md
> +Get the current selected items from the [`nodes`](https://ej2.syncfusion.com/vue/documentation/api/diagram/selectorModel/#nodes-nodemodel%5B%5D) and [`connectors`](https://ej2.syncfusion.com/vue/docu
reverted

2023-11-23 06:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176927-Vue-Page-With-Redirect-Links](https://jenkins.syncfusion.com/job/Content/job/ej2-vue-docs/131/console)**

2023-11-23 06:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176927-Vue-Page-With-Redirect-Links](https://jenkins.syncfusion.com/job/Content/job/ej2-vue-docs/131/)<br/>**

2023-11-23 07:06 UTC, Yvone-Atieno approved these changes
Approved

2023-12-03 15:37 UTC, Aishwarya-Ganesan approved these changes
fine.

2023-12-03 15:37 UTC, merged